/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTICPLUGIN_MESHTASTIC_INSPECTOR_PB_H_INCLUDED
#define PB_MESHTASTICPLUGIN_MESHTASTIC_INSPECTOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _meshtasticplugin_PacketRequest {
    pb_callback_t payload; /* Original MQTT payload (Meshtastic packet) */
    pb_callback_t ip_address; /* IP address of the client */
    pb_callback_t username; /* MQTT username */
    pb_callback_t client_id; /* MQTT client ID */
    pb_callback_t topic; /* MQTT topic */
    int64_t timestamp; /* Server/broker-side timestamp (epoch seconds) */
} meshtasticplugin_PacketRequest;

typedef struct _meshtasticplugin_PacketResponse {
    pb_callback_t payload; /* (Optional) Modified payload */
    bool shouldBlock; /* If true, broker should block/drop the message */
    pb_callback_t blockReason; /* The reason for blocking */
} meshtasticplugin_PacketResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtasticplugin_PacketRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define meshtasticplugin_PacketResponse_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define meshtasticplugin_PacketRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define meshtasticplugin_PacketResponse_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define meshtasticplugin_PacketRequest_payload_tag 1
#define meshtasticplugin_PacketRequest_ip_address_tag 2
#define meshtasticplugin_PacketRequest_username_tag 3
#define meshtasticplugin_PacketRequest_client_id_tag 4
#define meshtasticplugin_PacketRequest_topic_tag 5
#define meshtasticplugin_PacketRequest_timestamp_tag 6
#define meshtasticplugin_PacketResponse_payload_tag 1
#define meshtasticplugin_PacketResponse_shouldBlock_tag 2
#define meshtasticplugin_PacketResponse_blockReason_tag 3

/* Struct field encoding specification for nanopb */
#define meshtasticplugin_PacketRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           1) \
X(a, CALLBACK, SINGULAR, STRING,   ip_address,        2) \
X(a, CALLBACK, SINGULAR, STRING,   username,          3) \
X(a, CALLBACK, SINGULAR, STRING,   client_id,         4) \
X(a, CALLBACK, SINGULAR, STRING,   topic,             5) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         6)
#define meshtasticplugin_PacketRequest_CALLBACK pb_default_field_callback
#define meshtasticplugin_PacketRequest_DEFAULT NULL

#define meshtasticplugin_PacketResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           1) \
X(a, STATIC,   SINGULAR, BOOL,     shouldBlock,       2) \
X(a, CALLBACK, SINGULAR, STRING,   blockReason,       3)
#define meshtasticplugin_PacketResponse_CALLBACK pb_default_field_callback
#define meshtasticplugin_PacketResponse_DEFAULT NULL

extern const pb_msgdesc_t meshtasticplugin_PacketRequest_msg;
extern const pb_msgdesc_t meshtasticplugin_PacketResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtasticplugin_PacketRequest_fields &meshtasticplugin_PacketRequest_msg
#define meshtasticplugin_PacketResponse_fields &meshtasticplugin_PacketResponse_msg

/* Maximum encoded size of messages (where known) */
/* meshtasticplugin_PacketRequest_size depends on runtime parameters */
/* meshtasticplugin_PacketResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
