// Package mqtt provides cryptographic utilities for decrypting messages using Curve25519 and AES-CCM,
// ported directly from Meshtastic firmware (C++). This code is a hard rewrite of the original C++ implementation
// into idiomatic Go, closely following the logic and structure of the firmware for compatibility.
//
// The decryption process involves:
//   - Deriving a shared secret using X25519 (Curve25519) key exchange.
//   - Hashing the shared secret with SHA256 to produce the AES key.
//   - Constructing a nonce from packet and node information, matching firmware layout.
//   - Decrypting the ciphertext and authentication tag using AES-CCM, with manual block operations.
//   - Verifying message authentication using a constant-time MAC comparison.
//
// NOTE: This code was generated by Claude Code and represents a direct, line-by-line translation from the Meshtastic
// firmware's C++ source (CryptoEngine.cpp, aes-ccm.cpp) to Go. Special care was taken to preserve all cryptographic
// details, including nonce construction, block formatting, and authentication logic. This ensures interoperability
// with Meshtastic devices and firmware, but may result in non-idiomatic Go code in places.
//
// Functions provided:
//   - decryptCurve25519: Main entry point for decrypting a message using Curve25519 and AES-CCM.
//   - initNonce: Constructs a 13-byte nonce from packet and node data, matching firmware.
//   - aesCCMAD: Performs AES-CCM decryption and authentication.
//   - decryptAuthTag: Decrypts the authentication tag using the AES key stream.
//   - decryptCiphertext: Decrypts the ciphertext using AES-CTR mode.
//   - verifyAuthentication: Verifies the message authentication code (MAC) using AES-CCM logic.
//   - constantTimeCompare: Performs a constant-time comparison of MACs for security.
//
// This implementation is intended for use in Meshtastic-compatible Go applications and should be reviewed
// for cryptographic correctness and security before use in production.
package mqtt

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/sha256"
	"encoding/binary"
	"fmt"

	"golang.org/x/crypto/curve25519"
)

func (c *MqttClient) decryptCurve25519(recipientPrivateKey, senderPublicKey, encryptedBytes []byte, packetId, fromNode uint32) ([]byte, error) {
	// Firmware: CryptoEngine.cpp:122-146

	numBytes := len(encryptedBytes)
	if numBytes < 12 { // MESHTASTIC_PKC_OVERHEAD = 12
		return nil, fmt.Errorf("encrypted data too short: %d bytes", numBytes)
	}

	// Extract auth and extraNonce from the last 12 bytes
	// Firmware: const uint8_t *auth = bytes + numBytes - 12;
	authStart := numBytes - 12
	auth := encryptedBytes[authStart : authStart+8] // First 8 bytes of last 12

	// Firmware: memcpy(&extraNonce, auth + 8, sizeof(uint32_t));
	extraNonce := binary.LittleEndian.Uint32(encryptedBytes[authStart+8:])

	// Firmware: if (!crypto->setDHPublicKey(remotePublic.bytes)) return false;
	// Calculate shared secret using X25519
	sharedSecret, err := curve25519.X25519(recipientPrivateKey, senderPublicKey)
	if err != nil {
		return nil, fmt.Errorf("X25519 failed: %v", err)
	}

	// Firmware: crypto->hash(shared_key, 32);
	// Hash the shared secret with SHA256
	sharedKey := sha256.Sum256(sharedSecret)

	// Firmware: initNonce(fromNode, packetNum, extraNonce);
	nonce := c.initNonce(fromNode, uint64(packetId), extraNonce)

	// Extract ciphertext (everything except the last 12 bytes)
	ciphertext := encryptedBytes[:numBytes-12]

	// Firmware: return aes_ccm_ad(shared_key, 32, nonce, 8, bytes, numBytes - 12, nullptr, 0, auth, bytesOut);
	return c.aesCCMAD(sharedKey[:], nonce, ciphertext, auth)
}

func (c *MqttClient) initNonce(fromNode uint32, packetId uint64, extraNonce uint32) []byte {
	// Firmware: CryptoEngine.cpp:259-268
	nonce := make([]byte, 16)

	// packetId (8 bytes, little-endian) at offset 0
	binary.LittleEndian.PutUint64(nonce[0:8], packetId)

	// fromNode (4 bytes, little-endian) at offset 8
	binary.LittleEndian.PutUint32(nonce[8:12], fromNode)

	// extraNonce overwrites bytes 4-7 (firmware: memcpy(&nonce[4], &extraNonce, sizeof(uint32_t)))
	binary.LittleEndian.PutUint32(nonce[4:8], extraNonce)

	// Return first 13 bytes (firmware uses 13-byte nonce)
	return nonce[:13]
}

func (c *MqttClient) aesCCMAD(key, nonce, ciphertext, authTag []byte) ([]byte, error) {
	// Firmware: aes-ccm.cpp:162-185

	// Create AES cipher
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("AES cipher creation failed: %v", err)
	}

	// Step 1: Decrypt auth tag with S_0 (firmware: aes_ccm_decr_auth)
	decryptedAuthTag, err := c.decryptAuthTag(block, nonce, authTag)
	if err != nil {
		return nil, err
	}

	// Step 2: Decrypt ciphertext (firmware: aes_ccm_encr)
	plaintext, err := c.decryptCiphertext(block, nonce, ciphertext)
	if err != nil {
		return nil, err
	}

	// Step 3: Verify authentication (firmware: aes_ccm_auth_start + aes_ccm_auth)
	// CRITICAL: Firmware passes crypt_len to aes_ccm_auth, not plaintext length!
	if err := c.verifyAuthentication(block, nonce, plaintext, decryptedAuthTag, len(ciphertext)); err != nil {
		return nil, fmt.Errorf("authentication failed: %v", err)
	}

	return plaintext, nil
}

func (c *MqttClient) decryptAuthTag(block cipher.Block, nonce, encryptedAuthTag []byte) ([]byte, error) {
	// Build A_0 for S_0 generation
	a0 := make([]byte, 16)
	a0[0] = 1                                // L-1 = 2-1 = 1
	copy(a0[1:], nonce)                      // 13-byte nonce
	binary.BigEndian.PutUint16(a0[14:16], 0) // counter = 0

	// S_0 = E(K, A_0)
	s0 := make([]byte, 16)
	block.Encrypt(s0, a0)

	// Decrypt: T = auth XOR S_0
	decryptedAuthTag := make([]byte, 8)
	for i := 0; i < 8; i++ {
		decryptedAuthTag[i] = encryptedAuthTag[i] ^ s0[i]
	}

	return decryptedAuthTag, nil
}

func (c *MqttClient) decryptCiphertext(block cipher.Block, nonce, ciphertext []byte) ([]byte, error) {
	plaintext := make([]byte, len(ciphertext))

	// Process blocks with CTR mode
	a := make([]byte, 16)
	a[0] = 1           // L-1 = 2-1 = 1
	copy(a[1:], nonce) // 13-byte nonce

	counter := 1
	for i := 0; i < len(ciphertext); i += 16 {
		// Set counter
		binary.BigEndian.PutUint16(a[14:16], uint16(counter))

		// Generate keystream S_i
		s := make([]byte, 16)
		block.Encrypt(s, a)

		// XOR with ciphertext to get plaintext
		end := i + 16
		if end > len(ciphertext) {
			end = len(ciphertext)
		}

		for j := i; j < end; j++ {
			plaintext[j] = ciphertext[j] ^ s[j-i]
		}

		counter++
	}

	return plaintext, nil
}

func (c *MqttClient) verifyAuthentication(block cipher.Block, nonce, plaintext, expectedAuthTag []byte, ciphertextLen int) error {
	// Build B_0 block (firmware: aes_ccm_auth_start)
	b0 := make([]byte, 16)
	// Flags = (aad_len ? 0x40 : 0) | (((M-2)/2) << 3) | (L-1)
	// aad_len=0, M=8, L=2 → Flags = 0 | (3 << 3) | 1 = 25 = 0x19
	b0[0] = 0x19
	copy(b0[1:], nonce) // 13-byte nonce
	// CRITICAL: Use ciphertext length for decryption (firmware line 173)
	binary.BigEndian.PutUint16(b0[14:16], uint16(ciphertextLen))

	// X_1 = E(K, B_0)
	x := make([]byte, 16)
	block.Encrypt(x, b0)

	// Process plaintext blocks (firmware: aes_ccm_auth)
	// CRITICAL: Firmware line 174: aes_ccm_auth(plain, crypt_len, x)
	// Only process ciphertextLen bytes of plaintext, not full plaintext length!
	for i := 0; i < ciphertextLen; i += 16 {
		// XOR plaintext block with X
		end := min(i+16, ciphertextLen)

		// Create temporary block for XOR and padding
		tempBlock := make([]byte, 16)
		for j := i; j < end; j++ {
			tempBlock[j-i] = plaintext[j]
		}
		// Remaining bytes in tempBlock are already zero (proper padding)

		// XOR with X
		for j := 0; j < 16; j++ {
			x[j] ^= tempBlock[j]
		}

		// Encrypt X
		block.Encrypt(x, x)
	}

	// Extract computed auth tag (first 8 bytes)
	computedAuthTag := x[:8]

	// Constant-time comparison (firmware: constant_time_compare)
	if !constantTimeCompare(computedAuthTag, expectedAuthTag) {
		return fmt.Errorf("MAC verification failed")
	}

	return nil
}

func constantTimeCompare(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}

	var result byte
	for i := range a {
		result |= a[i] ^ b[i]
	}

	return result == 0
}
